#+TITLE: Appendix-F-Standard-Errors
* Appendix F Standard Errors
   :PROPERTIES:
   :CUSTOM_ID: appendix-f-standard-errors
   :END:

Here is a list of the more important error symbols in standard Emacs, grouped by concept. The list includes each symbol's message and a cross reference to a description of how the error can occur.

Each error symbol has a set of parent error conditions that is a list of symbols. Normally this list includes the error symbol itself and the symbol =error=. Occasionally it includes additional symbols, which are intermediate classifications, narrower than =error= but broader than a single error symbol. For example, all the errors in accessing files have the condition =file-error=. If we do not say here that a certain error symbol has additional error conditions, that means it has none.

As a special exception, the error symbol =quit= does not have the condition =error=, because quitting is not considered an error.

Most of these error symbols are defined in C (mainly data.c), but some are defined in Lisp. For example, the file userlock.el defines the =file-locked= and =file-supersession= errors. Several of the specialized Lisp libraries distributed with Emacs define their own error symbols. We do not attempt to list of all those here.

See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Errors][Errors]], for an explanation of how errors are generated and handled.

- =error=

  The message is 'error'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Errors][Errors]].

- =quit=

  The message is 'Quit'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Quitting][Quitting]].

- =args-out-of-range=

  The message is 'Args out of range'. This happens when trying to access an element beyond the range of a sequence, buffer, or other container-like object. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Sequences-Arrays-Vectors][Sequences Arrays Vectors]], and See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Text][Text]].

- =arith-error=

  The message is 'Arithmetic error'. This occurs when trying to perform integer division by zero. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Numeric-Conversions][Numeric Conversions]], and See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Arithmetic-Operations][Arithmetic Operations]].

- =beginning-of-buffer=

  The message is 'Beginning of buffer'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Character-Motion][Character Motion]].

- =buffer-read-only=

  The message is 'Buffer is read-only'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Read-Only-Buffers][Read Only Buffers]].

- =circular-list=

  The message is 'List contains a loop'. This happens when a circular structure is encountered. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Circular-Objects][Circular Objects]].

- =cl-assertion-failed=

  The message is 'Assertion failed'. This happens when the =cl-assert= macro fails a test. See [[https://www.gnu.org/software/emacs/manual/html_mono/cl.html#Assertions][Assertions]].

- =coding-system-error=

  The message is 'Invalid coding system'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Lisp-and-Coding-Systems][Lisp and Coding Systems]].

- =cyclic-function-indirection=

  The message is 'Symbol's chain of function indirections contains a loop'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Function-Indirection][Function Indirection]].

- =cyclic-variable-indirection=

  The message is 'Symbol's chain of variable indirections contains a loop'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Variable-Aliases][Variable Aliases]].

- =dbus-error=

  The message is 'D-Bus error'. This is only defined if Emacs was compiled with D-Bus support. See [[https://www.gnu.org/software/emacs/manual/html_mono/dbus.html#Errors-and-Events][Errors and Events]].

- =end-of-buffer=

  The message is 'End of buffer'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Character-Motion][Character Motion]].

- =end-of-file=

  The message is 'End of file during parsing'. Note that this is not a subcategory of =file-error=, because it pertains to the Lisp reader, not to file I/O. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Input-Functions][Input Functions]].

- =file-already-exists=

  This is a subcategory of =file-error=. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Writing-to-Files][Writing to Files]].

- =file-date-error=

  This is a subcategory of =file-error=. It occurs when =copy-file= tries and fails to set the last-modification time of the output file. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Changing-Files][Changing Files]].

- =file-error=

  We do not list the error-strings of this error and its subcategories, because the error message is normally constructed from the data items alone when the error condition =file-error= is present. Thus, the error-strings are not very relevant. However, these error symbols do have =error-message= properties, and if no data is provided, the =error-message= property /is/ used. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Files][Files]].

- =file-missing=

  This is a subcategory of =file-error=. It occurs when an operation attempts to act on a file that is missing. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Changing-Files][Changing Files]].

- =compression-error=

  This is a subcategory of =file-error=, which results from problems handling a compressed file. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#How-Programs-Do-Loading][How Programs Do Loading]].

- =file-locked=

  This is a subcategory of =file-error=. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#File-Locks][File Locks]].

- =file-supersession=

  This is a subcategory of =file-error=. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Modification-Time][Modification Time]].

- =file-notify-error=

  This is a subcategory of =file-error=. It happens, when a file could not be watched for changes. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#File-Notifications][File Notifications]].

- =ftp-error=

  This is a subcategory of =file-error=, which results from problems in accessing a remote file using ftp. See [[https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Remote-Files][Remote Files]].

- =invalid-function=

  The message is 'Invalid function'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Function-Indirection][Function Indirection]].

- =invalid-read-syntax=

  The message is 'Invalid read syntax'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Printed-Representation][Printed Representation]].

- =invalid-regexp=

  The message is 'Invalid regexp'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Regular-Expressions][Regular Expressions]].

- =mark-inactive=

  The message is 'The mark is not active now'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#The-Mark][The Mark]].

- =no-catch=

  The message is 'No catch for tag'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Catch-and-Throw][Catch and Throw]].

- =scan-error=

  The message is 'Scan error'. This happens when certain syntax-parsing functions find invalid syntax or mismatched parentheses. Conventionally raised with three argument: a human-readable error message, the start of the obstacle that cannot be moved over, and the end of the obstacle. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#List-Motion][List Motion]], and See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Parsing-Expressions][Parsing Expressions]].

- =search-failed=

  The message is 'Search failed'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Searching-and-Matching][Searching and Matching]].

- =setting-constant=

  The message is 'Attempt to set a constant symbol'. This happens when attempting to assign values to =nil=, =t=, =most-positive-fixnum=, =most-negative-fixnum=, and keyword symbols. It also happens when attempting to assign values to =enable-multibyte-characters= and some other symbols whose direct assignment is not allowed for some reason. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Constant-Variables][Constant Variables]].

- =text-read-only=

  The message is 'Text is read-only'. This is a subcategory of =buffer-read-only=. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Special-Properties][Special Properties]].

- =undefined-color=

  The message is 'Undefined color'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Color-Names][Color Names]].

- =user-error=

  The message is the empty string. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Signaling-Errors][Signaling Errors]].

- =user-search-failed=

  This is like 'search-failed', but doesn't trigger the debugger, like 'user-error'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Signaling-Errors][Signaling Errors]], and See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Searching-and-Matching][Searching and Matching]]. This is used for searching in Info files, See [[https://www.gnu.org/software/emacs/manual/html_mono/info.html#Search-Text][Search Text]].

- =void-function=

  The message is 'Symbol's function definition is void'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Function-Cells][Function Cells]].

- =void-variable=

  The message is 'Symbol's value as variable is void'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Accessing-Variables][Accessing Variables]].

- =wrong-number-of-arguments=

  The message is 'Wrong number of arguments'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Argument-List][Argument List]].

- =wrong-type-argument=

  The message is 'Wrong type argument'. See [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Type-Predicates][Type Predicates]].

