#+TITLE: Appendix-A-Emacs-25-Antinews
* Appendix A Emacs 25 Antinews
   :PROPERTIES:
   :CUSTOM_ID: appendix-a-emacs-25-antinews
   :END:

For those users who live backwards in time, here is information about downgrading to Emacs version 25.3. We hope you will enjoy the greater simplicity that results from the absence of many Emacs 26.3 features.

** A.1 Old Lisp Features in Emacs 25
    :PROPERTIES:
    :CUSTOM_ID: a.1-old-lisp-features-in-emacs-25
    :END:

- The concurrency features have been removed. Even in its limited "mostly cooperative" form, with only one Lisp thread running at any given time, it made Emacs significantly more complex for Lisp programs that need to work correctly in the presence of additional threads.\\
- Handling of file attributes has been simplified by discarding the accessor functions, such as =file-attribute-type= and =file-attribute-modification-time=. Real Lisp programmers always access the individual attributes by their ordinal numbers, and can recite those numbers in their sleep.\\
- The networking code is back at its pristine simplicity, as we deleted the use of asynchronous DNS resolution, connection, and TLS negotiation for TLS streams. You no longer need to consider the resulting complexity and interesting race conditions when you write Lisp programs that use network communications. As a direct consequence, the =:complete-negotiation= parameter of =gnutls-boot= has become unnecessary, and was removed---just one example of how removal of asynchronicity simplifies Emacs.\\
- We've removed the puny.el library, so Web sites with non-ASCII URLs are no longer easily accessible. But such sites become more and more rare as you move back in time, so having a specialized library for their support was deemed an unnecessary maintenance burden.\\
- The time conversion functions =current-time-string=, =current-time-zone=, =decode-time=, =format-time-string=, and =set-time-zone-rule= no longer accept integer offsets as time zone rules, to make it more of a challenge to convert foreign timestamps. Also, =format-time-string= no longer converts '%q' to the calendar quarter, as that is something you can easily do for yourself.\\
- Field numbers like '%2$' in format specifiers are no longer available. We decided that their use makes code reading and comprehension much harder, and that having them is unjustified in the past where similar features in popular C libraries will also be gone.\\
- Since the built-in capability to display line numbers has been removed (see [[https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Antinews][Antinews]]), we've also deleted the =line-number-display-width= function and the support for the =display-line-numbers-disable= property, as Lisp programs that do their own display layout decisions no longer need to cater to this tricky feature.\\
- Regular expressions have been simplified by removing support for Unicode character properties in the =[:blank:]= regexp class. As result, this class will match only spaces and tabs. Once again, this is in line with diminishing importance of Unicode as you move back in time.\\
- For similar reasons, we removed the function =char-from-name=. It should be easy enough to access the full list of Unicode characters returned by =ucs-names= instead, for as long as Unicode support in Emacs exists (which shouldn't be too long).\\
- Various functions that accept file names as arguments, such as =file-attributes=, =file-symlink-p=, and =make-symbolic-link= gained back the special support for file names quoted with '/:', and they now interpret '~' in symlink targets as you'd expect: to mean your home directory. The confusing differences between the operation of these functions in interactive and non-interactive invocations has been removed.\\
- Several functions that create or rename their files now treat their destination specially if it happens to be a directory, even when its name does not appear to be that of a directory. For example, =(rename-file "A" "B")= no longer renames A to B if B happens to be a directory. This is so that dealing with files becomes more of an adventure.\\
- The =format= function now returns new strings in more cases, to place more stress on the Emacs memory manager and thereby test Emacs better.\\
- The function assoc has been simplified by removing its third optional argument. It now always uses =equal= for comparison. Likewise, =alist-get= always uses =assq=, and =map-get= and =map-put= always use =eql= for their comparisons.\\
- Numeric comparisons and the functions =format=, =make-hash-table=, =min=, =max= and =logb= now occasionally round values internally to make their results less predictable.\\
- The functions =ffloor=, =fceiling=l, =ftruncate= and =fround= now accept integer arguments. Conversely, functions like =decode-char= that accept floating-point integers now accept arguments that are not integers. In both cases the results are amusingly nonsensical sometimes.\\
- GnuTLS cryptographic functions are no longer available in Emacs. We have decided that the needs for such functionality are deteriorating, and their cumbersome interfaces make them hard to use.\\
- We have removed support for records of user-defined types, and =cl-defstruct= no longer uses records. This removes the potential for quite a few places where existing and past code could be broken by records.\\
- You can again use =string-as-unibyte=, =string-make-multibyte=, and other similar functions, without being annoyed by messages about their deprecation. This is in preparation for removal of multibyte text from Emacs in the distant past.\\
- The =string-version-lessp= function has been removed, to encourage programmers to use their own idiosyncratic methods to determine whether one version string precedes another.\\
- The function =read-color= no longer displays color names using each color as the background. We have determined that this surprises users and produces funny inconsistent results on color-challenged terminals.\\
- Support for 24-bit color on text terminals has been dropped, since it wasn't needed long ago.\\
- We removed the function =file-name-case-insensitive-p=, as testing for the OS symbol should be enough for the observable past to come, and learning to use yet another API is a burden.\\
- The function =read-multiple-choice= is also gone, in recognition of the fact that nothing makes Emacs Lisp hackers rejoice more than the need to sit down and write yet another interactive question-and-answer function, and make it optimal for each specific case.\\
- The function =add-variable-watcher= and the corresponding debugger command =debug-on-variable-change= have been removed. They make debugging more complicated, while examining the value of a variable at each stop point is easy enough to cover the same use cases. Let simplicity rule!\\
- The function =mapcan= is gone; use =mapcar= instead, and process the resulting list as you see fit.\\
- Low-level list functions like =length= and =member= can now loop indefinitely when given cyclic lists, causing Emacs to freeze. This can help these functions run a tiny bit faster in the usual case where the input is not cyclic.\\
- The =write-region= function no longer propagates its lockname argument to file name handlers.\\
- You can once again write a Lisp program that returns funny random values from =file-attributes= by having another process alter the filesystem while Emacs is accessing the file. This can give rise to some interesting applications in the near past.\\
- The functions =file-attributes=, =file-symlink-p=, and =make-symbolic-link= now quietly mutate the target of a local symbolic link in some cases, to make it more of a challenge to deal with arbitrary symlinks in Emacs code.\\
- The error =file-missing= has been removed; operations now lump such errors into the =file-error= category instead.\\
- The function =delete-directory= now signals an error if operating recursively and some other process deletes the directory before this function gets to it.\\
- The =dutch= input method now attempts to support Turkish too, albeit incorrectly. Also, it converts 'IJ' and 'ij' to special characters instead of leaving them alone.\\
- Non-breaking hyphens and approximations to quotes are now displayed just with the =escape-glyph= face instead of having faces of their own. This is simpler and gives the user amusing puzzles to solve when viewing text containing these characters.\\
- The user option =electric-quote-context-sensitive= and the variable =electric-quote-inhibit-functions=, so that electric quoting is simpler and more likely to do the wrong thing.\\
- The user option =text-quoting-style= has been removed, and is now just a variable.\\
- We have removed the functions =file-name-quote=, =file-name-unquote=, and =file-name-quoted-p=. Writing code that checks whether a file name is already quoted is easy, and doubly quoting a file name should not produce any problems for well-written Lisp code.\\
- Frame parameters like =z-group=, =min-width=, =parent-frame=, =delete-before=, etc. have been removed. Emacs should not replace your window-manager, certainly not as window-managers become less and less capable.\\
- We decided that the format of mode line and header line should be customizable only based on buffers; the =mode-line-format= and =header-line-format= window parameters have been removed.\\
- Emacs now normally builds a limited movemail substitute that retrieves POP3 email only via insecure channels, and the configure-time option --with-mailutils has been removed. This simplifies Emacs setup when security is not important.\\
- The configure-time option --enable-gcc-warnings=warn-only has been removed, so that build-time warnings are always fatal now.\\
- The configure-time option --disable-build-details has been removed. This way, Emacs builds are unique and irreproducible.\\
- The variable =emacs-version= now includes the build number instead of storing it separately in =emacs-build-number=.\\
- Emacs has been ported to IRIX.\\
- Several options and variables have been removed to simplify Emacs and potentially make it less reliable. These include the --module-assertions option, the =attempt-stack-overflow-recovery= variable, and the =attempt-orderly-shutdown-on-fatal-signal= variable.\\
- As part of the ongoing quest for simplicity, many other functions and variables have been eliminated.

Next: [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#GPL][GPL]], Previous: [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Antinews][Antinews]], Up: [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Top][Top]]
